config/routes.rb
Rails.application.routes.draw do
  resources :challenges, only:[:index, :show]
  resources :attempts, only:[:create]

  get "/reset", to: "attempts#reset"

  root to: "challenges#index"
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  default_scope { order(:order) }
  store_accessor :metadata, :tables, :topic

  def next
    self.class.find_by(order: order + 1)
  end

  def previous
    self.class.find_by(order: order - 1) || Challenge.first
  end

  def schema
    tables.map do |table_name|
      TableInfo.schema_for(table_name)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ChallengeConcern
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  def create
    challenge = Challenge.find_by(id: attempt_params[:challenge_id])
    valid_attempt = Attempt.is_correct?(attempt_params[:query], challenge.query)

    flash[:query] = attempt_params[:query]

    if valid_attempt
      flash[:notice] = "Correct!"
      session[:challenge_id] = challenge.id
      redirect_to challenge.next ? challenge.next : root_path
    else
      flash[:alert] = "Incorrect"
      redirect_to challenge
    end

  end

  def reset
    session.clear
    redirect_to root_path
  end

  private

  def attempt_params
    params.require(:attempt).permit(:query, :challenge_id)
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  before_action :load_challenge, :set_previous_results, only: [:show]

  def index
    @challenges = Challenge.all
    @progress = session.fetch(:challenge_id) {0}
  end

  def show
    @metadata = @challenge.schema
  end

  private

  def load_challenge
    @challenge = Challenge.find_by(id: params[:id])
  end

  def set_previous_results
    return unless previous_query?
    last_guess_correct = flash[:notice].present?
    expected = last_guess_correct ? @challenge.previous.query : @challenge.query
    @last_query = Attempt.results_for(flash[:query])
    @expected = Attempt.results_for(expected)
  end

end

app/controllers/concerns/challenge_concern.rb
module ChallengeConcern
  extend ActiveSupport::Concerns

  def previous_query?
    flash[:query].present?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def challenges_by_topic(challenges)
    challenges.group_by(&:topic)
  end

  def progress_value
    @progress.to_f / @challenges.count.to_f
  end

  def start_button_text
    is_new_user ? "Start" : "Continue"
  end

  def is_new_user
    @progress == 0
  end

  def last_challenge
    Challenge.find_by(order: session[:challenge_id])
  end

  def next_challenge
    session[:challenge_id] ? last_challenge.next : Challenge.first
  end

  def display_last_query
    if @last_query
      "Last Query:  #{flash[:query]}"
    end
  end

end

app/views/challenges/_challenge.html.slim
.challenge-item.truncate
  = link_to challenge.instructions, challenge_path(challenge)

app/views/challenges/_editor.slim
= form_tag("/attempts", class: "md-col md-col-12") do |t|
  = hidden_field_tag("attempt[challenge_id]", @challenge.id)
  = text_area_tag("attempt[query]", flash[:query], class: "sql-textarea md-col md-col-12 border-none")
  .btn.block.clear.p0.mt1
    = submit_tag("Run", class: "btn btn-primary md-col-12 mt2")

  script
    | ST.autoHighlightQueryText.init()

app/views/challenges/_schema.html.slim
- tables.each do |table|
  table.border.rounded.mb2.h5
    th.blue.border-bottom.bg-silver
      = table[:table_name]
    - table[:fields].each do |field|
      tr
        td.border-bottom
          =field

app/views/challenges/index.html.slim
.container
  .header.h1.mt2
    | SQL Tutor
  hr.mb3

  ul.challenges.md-col.md-col-7
    - challenges_by_topic(@challenges).each_pair do |topic, challenges|
      .panel.border-top.border-left.rounded.mb3.md-col.md-col-11
        .topic.bg-silver.px1.h3
          = topic
        .sub-challenges.p2.bg-white
          = render challenges

  .progress.md-col.md-col-3
    .progress-indicator.mb2
      progress.progress.muted value="#{progress_value}" = progress_value
      .progress-text.right-align
        = "#{@progress} of #{@challenges.count} challenges completed"

    .progress-functions.md-col.md-col-12
      .continue.md-col.md-col-12.right-align
        = link_to "#{start_button_text}", next_challenge, class: "btn btn-primary mb2 .md-col md-col-8 center"

    - if is_new_user
      .reset.md-col.md-col-12.right-align.hide
    - else 
      .reset.md-col.md-col-12.right-align
        = link_to "Reset Progress", reset_path, class: "btn btn-primary bg-red mb2 .md-col md-col-8 center"

app/views/challenges/show.html.slim
.messages.center.white
  .notice.bg-green
    = flash[:notice]
  .alert.bg-red.white
    = flash[:alert]

.container
  .header.h1.mt2
    = link_to "SQL Tutor", root_path
  hr
  .challenge
    .challenge-left.md-col.md-col-9
      .instructions.py2.h2.md-col.md-col-10
        = @challenge.instructions

      .attempt.md-col.md-col-10.bg-silver.rounded.p2
        .attempt-form.md-col.md-col-12
          = render "editor"

        .clear
        .query.md-col.md-col-12
          .h5.mt2
             = display_last_query

    .challenge-right.md-col.md-col-3
      .h2.mt1 Table Info
      .metadata.p2.mt1
        = render "schema", tables: @metadata

    .hr
    .results.md-col.md-col-12.mb3
      .actual.md-col.md-col-6
        - if @last_query && @last_query.key?(:fields)
          h4 Your Results
          .query-results-table.overflow-scroll.mr2.border.rounded
            = render "shared/query_results", results: @last_query
        - elsif @last_query && @last_query.key?(:error)
          h4 Your Results
          .query-results-table.overflow-scroll.mr1
            = @last_query[:error]
      .expected.md-col.md-col-6
        - if @expected
          h4 Expected Results
          .query-results-table.overflow-scroll.mr2.border.rounded
            = render "shared/query_results", results: @expected

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SqlTutor</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_query_results.html.slim
table
  tr.headers
    - results[:fields].each do |field_name|
      th.blue.border-top.bg-silver =field_name
  - results[:rows].each do |row_data|
    tr
      - row_data.each do |k, v|
        td.border-top =v